// Frontend/todo-ui/src/app/add-todo/add-todo.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { Todo } from '../models/todo';
import { AppContext } from '../app.context';
import { TodoService } from '../services/todo.service';
import { Status } from '../enum/Status';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent implements OnInit {

  public todoName: string;
  @Output()
  public addedEvent:EventEmitter<Todo> = new EventEmitter<Todo>();

  constructor(public appContext: AppContext, private todoService: TodoService) { }

  public ngOnInit(): void {
  }

  public onSubmit(): void {
    let todo = new Todo(null, this.todoName, Status.Todo, null, this.appContext.username, null, null);

    this.todoService.add(todo)
      .subscribe(todo => {
        this.addedEvent.emit(todo);
        this.todoName = null
      })
  }

}

<div class="add-todo">
		<div class="add-screen">
			<div class="add-todo-form">
				<div class="control-group">
				<input type="text" class="add-todo-field"  placeholder="Todo Name" id="add-todo-name" [(ngModel)]="todoName">
				<label class="add-todo-field-icon fui-user" for="add-todo-name"></label>
        </div>
				<button class="btn btn-primary btn-large btn-block" (click)="onSubmit()">Add</button>
			</div>
		</div>
	</div>

// Frontend/todo-ui-react/src/components/add-todo/add-todo.js
import React, { Component } from 'react';
import './add-todo.css';
import { Todo } from '../../models/todo';
import {AppSettings} from '../../appsettings';
import { TodoService } from '../../services/todo-service';


class AddTodo extends Component {

  todoService = new TodoService();

  constructor(){
    super();
    this.state = {todoName: ""}
  }

  onNameChange = (e) => {
    this.setState({todoName : e.target.value})
  }

  addTodo = () => {
    let todo = new Todo(null, this.state.todoName, "InProgress", null, AppSettings.username, null, null);
    this.todoService.add(todo).then(x => {
      this.props.todoAdded(x.data)
    })
    this.setState({todoName: ""})
  }

  render() {
    return (
      <div className="add-todo">
        <div className="add-screen">
          <div className="add-todo-form">
            <div className="control-group">
              <input type="text" className="add-todo-field" placeholder="Todo Name" id="add-todo-name" value={this.state.todoName} onChange={this.onNameChange}/>
              <label className="add-todo-field-icon fui-user"></label>
            </div>
            <button className="add-btn btn-primary btn-large btn-block" onClick={() => this.addTodo()} >Add</button>
          </div>
        </div>
      </div>
    );
  }
}

export default AddTodo;
