// Frontend/todo-ui-react/src/components/auth/registration/registration.js
import React, { Component } from 'react';
import './registration.css';
import { AuthService } from '../../../services/auth-service'

class Registration extends Component {

    authService = new AuthService()

    constructor() {
        super();
        this.state = {
            form: {
                firstName: {name :"First Name", value: ""},
                lastName: {name :"Last Name", value: ""},
                userName: {name :"Username", value: ""},
                password:{name :"Password", value: ""}
            }
        }
    }

    registerClick = () => {
        this.props.registrationClick(false)
    }

    onSubmit = () => {
        let username = this.state.form.userName.value
        let password = this.state.form.password.value

        this.authService.register({
            firstName: this.state.form.firstName.value,
            lastName: this.state.form.lastName.value,
            userName: this.state.form.userName.value,
            password:this.state.form.password.value
        }).then(x => {
            this.login(username,password)
        })
    }

    onChange = (key, e) => {
        this.state.form[key].value = e.target.value
        this.setState(this.state)
    }
    
    login = (username, password) => {
        this.authService.signin(username, password).then(x => {
            if(x.data.accessToken){
                localStorage.setItem("accessToken", x.data.accessToken)
                window.location.href = '/'
            }
        })
    }
    render() {
       let formFields = []
        Object.keys(this.state.form).forEach(key => {
            formFields.push(
            <div key={this.state.form[key].name} className="registration-control-group">
                <input type="text" className="registration-field" value={this.state.form[key].value} onChange={(e) => this.onChange(key ,e)} placeholder={this.state.form[key].name} />
            </div>
            )
        })
 
        return (
            <div className="registration">
                <div className="registration-screen">
                    <div className="app-title">
                        <h1>Registration</h1>
                    </div>
                    <div className="registration-form">
                        {formFields}
                        <div className="registration-control-group">
                            <button className="btn btn-primary btn-large btn-block" onClick={this.onSubmit}>Register</button>
                            <button className="btn btn-primary btn-large btn-block register" onClick={this.registerClick}>Back To Login</button>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Registration;

// Frontend/todo-ui/src/app/auth/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/models/user';
import { UserService } from 'src/app/services/user.service';
import { Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent implements OnInit {

  public model : User 

  public error: boolean = false

  constructor(private userService:UserService, private router: Router, private authservice: AuthService) { 
    this.model = new User(null,null,null,null,null);
  }

  ngOnInit() {
    
  }

  public onSubmit():void{
    this.userService.insertUser(this.model)
    .subscribe(res => this.login(),
      error => this.error = true)
  }

  public login():void{
    if (this.model.userName && this.model.password) {
      this.authservice.signin(this.model.userName , this.model.password)
        .subscribe(x => {
          if (x.accessToken) {
            localStorage.setItem("accessToken", x.accessToken)
            this.router.navigate(["/home"])
          }
        })
    }
  }

}

<div class="registration">
  <div class="registration-screen">
    <div class="app-title">
      <h1>Registration</h1>
    </div>

    <div class="registration-form">

      <div class="control-group">
        <input type="text" class="registration-field" placeholder="First Name" [(ngModel)]="model.firstName">
        <label class="registration-field-icon fui-user" for="registration-name"></label>
      </div>

      <div class="control-group">
        <input type="text" class="registration-field" placeholder="Last Name" [(ngModel)]="model.lastName">
        <label class="registration-field-icon fui-user" for="registration-name"></label>
      </div>
      <div *ngIf="error">
        <p class="error-text">Username Already Exists</p>
      </div>

      <div class="control-group">
        <input type="text" class="registration-field" placeholder="Username" id="registration-name" [(ngModel)]="model.userName">
        <label class="registration-field-icon fui-user" for="registration-name"></label>
      </div>

      <div class="control-group">
        <input type="password" class="registration-field" placeholder="Password" id="registration-pass" [(ngModel)]="model.password">
        <label class="registration-field-icon fui-lock" for="registration-pass"></label>
      </div>

      <button class="btn btn-primary btn-large btn-block" (click)="onSubmit()">Register</button>
    </div>
  </div>
</div>
