// Frontend/todo-ui/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  public username: string;
  public password: string;

  constructor(private authservice: AuthService, private router: Router) { }

  ngOnInit() {
  }

  public onSubmit() {
    if (this.username && this.password) {
      this.authservice.signin(this.username, this.password)
        .subscribe(x => {
          if (x.accessToken) {
            localStorage.setItem("accessToken", x.accessToken)
            this.router.navigate(["/home"])
          }
        })
    }
  }

}

<div class="login">
  <div class="login-screen">
    <div class="app-title">
      <h1>Login</h1>
    </div>

    <div class="login-form">
      <div class="control-group">
      <input type="text" class="login-field"  placeholder="username" id="login-name" [(ngModel)]="username">
      <label class="login-field-icon fui-user" for="login-name"></label>
      </div>

      <div class="control-group">
      <input type="password" class="login-field" value="" placeholder="password" id="login-pass" [(ngModel)]="password">
      <label class="login-field-icon fui-lock" for="login-pass"></label>
      </div>

      <button class="btn btn-primary btn-large btn-block" (click)="onSubmit()">login</button>
    </div>
  </div>
</div>

// Frontend/todo-ui-react/src/components/auth/login/login.js
import React, { Component } from 'react';
import './login.css';
import { AuthService } from '../../../services/auth-service'

class Login extends Component {

    authService = new AuthService()

    constructor() {
        super();
        this.state = {
            username: '',
            password: ''
        }

    }

    login = () => {
        this.authService.signin(this.state.username, this.state.password)
        .then(x => {
            if(x.data.accessToken){
            localStorage.setItem("accessToken", x.data.accessToken)
            window.location.href = '/'
            }
        })
    }

    handleUsername = (event) => {
        this.setState({ username: event.target.value });
    }
    handlePassword = (event) => {
        this.setState({ password: event.target.value });
    }

    registerClick = () => {
        this.props.registrationClick(true)
    }

    

    render() {
        return (
            <div className="login">
                <div className="login-screen">
                    <div className="app-title">
                        <h1>Login</h1>
                    </div>
                    <div className="login-form">
                        <div className="login-control-group">
                            <input type="text" className="login-field" placeholder="Username" value={this.state.username} onChange={this.handleUsername} id="login-name" />
                        </div>

                        <div className="login-control-group">
                            <input type="password" className="login-field" placeholder="Password" value={this.state.password} onChange={this.handlePassword} id="login-pass" />
                        </div>

                        <button className="btn btn-primary btn-large btn-block" onClick={this.login}>Login</button>
                        <button className="btn btn-primary btn-large btn-block register" onClick={this.registerClick}>Register</button>
                    </div>
                </div>
            </div>
        );
    }
}

export default Login;
