// Frontend/todo-ui/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from '../models/todo';
import { Router } from '@angular/router';
import { AppContext } from '../app.context';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  public addedItem:Todo

  constructor(private router: Router, private appContext: AppContext) { }

  ngOnInit() {
  }

  public addedEvent(todo:Todo): void{
    this.addedItem = todo;
  }

  public logout():void{
    localStorage.removeItem("accessToken")
    this.router.navigate(["/login"])
  }

}

<div class="container">
    <div class="app-title">
        <h1>Add Todo</h1>
        <button class="btn logout" (click)="logout()">Logout</button>
        <p>{{appContext.userName}}</p>
    </div>
    <app-add-todo (addedEvent)="addedEvent($event)"></app-add-todo>
    <app-list-todo [addedItem]="addedItem"></app-list-todo>
</div>

// Frontend/todo-ui-react/src/components/home/home.js
import React, { Component } from 'react';
import './home.css';
import AddTodo from '../add-todo/add-todo';
import ListTodo from '../list-todo/list-todo';
import {AppSettings} from '../../appsettings'

class Home extends Component {

  constructor(){
    super();
    this.state = {todoAdded : null} 
  }

  logout = () => {
    localStorage.removeItem("accessToken")
    window.location.href = "/login"
  }

  todoAdded = (todo) => {
    this.setState({todoAdded: todo})
  }

  render() {
    return (
      <div className="home-container">
        <div className="app-title-home">
          <h1>Add Todo</h1>
          <button className="btn-logout" onClick={this.logout}>Logout</button>
          <p>{AppSettings.username}</p>
        </div>
        <AddTodo todoAdded={this.todoAdded} />
        <ListTodo todoAdded={this.state.todoAdded} />
      </div>
    );
  }
}

export default Home;
